export * as teamService from './team.service'
export * as papelitoService from './papelito.service'
export * as playerService from './player.service'
export * as roomService from './room.service'
export * as gameService from './game.service'
