export enum GameActions {}
// CREATE_ROOM,
// JOIN_ROOM,

// GET_ALL_PLAYERS,
// GET_PLAYER,
// ADD_PLAYER,
// REMOVE_PLAYER,

// GET_ALL_TEAMS,
// ADD_TEAM,
// REMOVE_TEAM,
// ADD_PLAYER_TO_TEAM,
// REMOVE_PLAYER_FROM_TEAM,

// GET_ALL_PAPELITOS,
// ADD_PAPELITO,
// REMOVE_PAPELITO,
// THROW_PAPELITO_IN_BOWL,

// GET_ALL_PAPELITOS_IN_BOWL,
// DRAW_PAPELITO_FROM_BOWL,
// UNDRAW_PAPELITO_FROM_BOWL,
// GUESS_PAPELITO_FROM_BOWL,

// START_TIMER,
// STOP_TIMER,

export type Action<T> = { type: GameActions; payload?: T }
